/// Quasar Interface Verification Tests (Phase 3)
///
/// Verifies that coral_xyz correctly parses real Quasar-generated IDL files.
/// Tests cover: format detection, metadata, discriminators, type parsing,
/// PDA seeds, events, errors, hasRemaining, zero-copy encoding/decoding,
/// and instruction encoding.
///
/// All IDL fixtures are generated by the real Quasar CLI from the quasar/
/// repository programs. No synthetic test data.
library;

import 'dart:convert';
import 'dart:typed_data';

import 'package:coral_xyz/coral_xyz.dart';
import 'package:test/test.dart';

import 'verification_helpers.dart';

// ============================================================
// Helpers
// ============================================================

/// Load a Quasar IDL fixture and return both raw JSON and parsed Idl.
({Map<String, dynamic> json, Idl idl}) _load(String filename) {
  final json = loadFixtureJson(filename);
  final idl = Idl.fromJson(json);
  return (json: json, idl: idl);
}

/// Find an instruction by name in a parsed Idl.
IdlInstruction _ix(Idl idl, String name) =>
    idl.instructions.firstWhere((i) => i.name == name);

/// Find a type definition by name.
IdlTypeDef _type(Idl idl, String name) =>
    (idl.types ?? []).firstWhere((t) => t.name == name);

/// Find an account by name.
IdlAccount _acct(Idl idl, String name) =>
    (idl.accounts ?? []).firstWhere((a) => a.name == name);

/// Find an event by name.
IdlEvent _evt(Idl idl, String name) =>
    (idl.events ?? []).firstWhere((e) => e.name == name);

/// Find an instruction account by name.
IdlInstructionAccount _ixAcct(IdlInstruction ix, String name) {
  for (final item in ix.accounts) {
    if (item is IdlInstructionAccount && item.name == name) return item;
  }
  throw StateError('Account "$name" not found in instruction "${ix.name}"');
}

/// Decode const seed bytes to string (for UTF-8 literal seeds).
String _seedToString(IdlSeed seed) {
  if (seed is IdlSeedConst) {
    return utf8.decode(seed.value);
  }
  throw StateError('Not a const seed: $seed');
}

void main() {
  // ============================================================
  // Group 1: Format Detection — all 7 IDLs detected as Quasar
  // ============================================================
  group('1. Format detection', () {
    final fixtures = [
      'quasar_vault.idl.json',
      'quasar_escrow.idl.json',
      'quasar_test_misc.idl.json',
      'quasar_test_events.idl.json',
      'quasar_test_pda.idl.json',
      'quasar_test_errors.idl.json',
      'quasar_multisig.idl.json',
    ];

    for (final f in fixtures) {
      test('$f detected as Quasar', () {
        final json = loadFixtureJson(f);
        final format = IdlFormat.detect(json);
        print('  $f → $format');
        expect(format, IdlFormat.quasar);
      });
    }
  });

  // ============================================================
  // Group 2: Metadata Parsing
  // ============================================================
  group('2. Metadata parsing', () {
    test('vault metadata', () {
      final r = _load('quasar_vault.idl.json');
      expect(r.idl.metadata?.name, 'quasar_vault');
      expect(r.idl.metadata?.version, '0.1.0');
      print('  name=${r.idl.metadata?.name} ver=${r.idl.metadata?.version}');
    });

    test('escrow metadata', () {
      final r = _load('quasar_escrow.idl.json');
      expect(r.idl.metadata?.name, 'quasar_escrow');
    });

    test('test_misc metadata', () {
      final r = _load('quasar_test_misc.idl.json');
      expect(r.idl.metadata?.name, 'quasar_test_misc');
    });

    test('program address parsed', () {
      final r = _load('quasar_vault.idl.json');
      expect(r.idl.address, '33333333333333333333333333333333333333333333');
      print('  address=${r.idl.address}');
    });
  });

  // ============================================================
  // Group 3: Instruction Discriminators (explicit, single-byte)
  // ============================================================
  group('3. Instruction discriminators', () {
    test('vault: sequential 0,1', () {
      final r = _load('quasar_vault.idl.json');
      expect(_ix(r.idl, 'deposit').discriminator, [0]);
      expect(_ix(r.idl, 'withdraw').discriminator, [1]);
      print('  deposit=[0], withdraw=[1]');
    });

    test('escrow: sequential 0,1,2', () {
      final r = _load('quasar_escrow.idl.json');
      expect(_ix(r.idl, 'make').discriminator, [0]);
      expect(_ix(r.idl, 'take').discriminator, [1]);
      expect(_ix(r.idl, 'refund').discriminator, [2]);
    });

    test('test_errors: discriminators with gaps (18→20)', () {
      final r = _load('quasar_test_errors.idl.json');
      // Instructions 0-17, then gap to 20
      expect(_ix(r.idl, 'headerDupSigner').discriminator, [17]);
      expect(_ix(r.idl, 'systemAccountCheck').discriminator, [20]);
      print('  gap: [17] → [20]');
    });

    test('test_misc: discriminator gap (16→20) and (24→26→27)', () {
      final r = _load('quasar_test_misc.idl.json');
      expect(_ix(r.idl, 'remainingAccountsCheck').discriminator, [16]);
      expect(_ix(r.idl, 'dynamicAccountCheck').discriminator, [20]);
      expect(_ix(r.idl, 'dynamicReadback').discriminator, [24]);
      expect(_ix(r.idl, 'dynamicMutate').discriminator, [26]);
      expect(_ix(r.idl, 'mutateThenReadback').discriminator, [27]);
      // Big gap to 41
      expect(_ix(r.idl, 'doubleMutCheck').discriminator, [41]);
      print('  last disc=[41], verifying gaps');
    });
  });

  // ============================================================
  // Group 4: Account Discriminators (explicit, single & multi-byte)
  // ============================================================
  group('4. Account discriminators', () {
    test('escrow: Escrow disc=[1]', () {
      final r = _load('quasar_escrow.idl.json');
      expect(_acct(r.idl, 'Escrow').discriminator, [1]);
    });

    test('test_misc: single-byte account discs', () {
      final r = _load('quasar_test_misc.idl.json');
      expect(_acct(r.idl, 'SimpleAccount').discriminator, [1]);
      expect(_acct(r.idl, 'DynamicAccount').discriminator, [5]);
      expect(_acct(r.idl, 'MixedAccount').discriminator, [6]);
      expect(_acct(r.idl, 'SmallPrefixAccount').discriminator, [7]);
      expect(_acct(r.idl, 'TailStrAccount').discriminator, [8]);
      expect(_acct(r.idl, 'TailBytesAccount').discriminator, [9]);
    });

    test('test_misc: MultiDiscAccount has 2-byte discriminator [1,2]', () {
      final r = _load('quasar_test_misc.idl.json');
      final disc = _acct(r.idl, 'MultiDiscAccount').discriminator;
      expect(disc, [1, 2]);
      expect(disc.length, 2);
      print('  MultiDiscAccount disc=$disc (${disc.length} bytes)');
    });

    test('test_pda: sequential account discs 1-7', () {
      final r = _load('quasar_test_pda.idl.json');
      expect(_acct(r.idl, 'ConfigAccount').discriminator, [1]);
      expect(_acct(r.idl, 'UserAccount').discriminator, [2]);
      expect(_acct(r.idl, 'ItemAccount').discriminator, [3]);
      expect(_acct(r.idl, 'ComplexAccount').discriminator, [4]);
      expect(_acct(r.idl, 'EmptySeedAccount').discriminator, [5]);
      expect(_acct(r.idl, 'MaxSeedAccount').discriminator, [6]);
      expect(_acct(r.idl, 'ThreeSeedAccount').discriminator, [7]);
    });
  });

  // ============================================================
  // Group 5: Event Discriminators
  // ============================================================
  group('5. Event discriminators', () {
    test('escrow: 3 events with sequential discs', () {
      final r = _load('quasar_escrow.idl.json');
      final events = r.idl.events ?? [];
      expect(events.length, 3);
      expect(_evt(r.idl, 'MakeEvent').discriminator, [0]);
      expect(_evt(r.idl, 'TakeEvent').discriminator, [1]);
      expect(_evt(r.idl, 'RefundEvent').discriminator, [2]);
    });

    test('test_events: 7 events with discs 1-7', () {
      final r = _load('quasar_test_events.idl.json');
      final events = r.idl.events ?? [];
      expect(events.length, 7);
      expect(_evt(r.idl, 'SimpleEvent').discriminator, [1]);
      expect(_evt(r.idl, 'AddressEvent').discriminator, [2]);
      expect(_evt(r.idl, 'BoolEvent').discriminator, [3]);
      expect(_evt(r.idl, 'MultiEvent').discriminator, [4]);
      expect(_evt(r.idl, 'EmptyEvent').discriminator, [5]);
      expect(_evt(r.idl, 'LargeEvent').discriminator, [6]);
      expect(_evt(r.idl, 'SecondSimpleEvent').discriminator, [7]);
    });

    test('event type definitions match event names', () {
      final r = _load('quasar_test_events.idl.json');
      final types = r.idl.types ?? [];
      final events = r.idl.events ?? [];
      for (final evt in events) {
        final typeDef = types.where((t) => t.name == evt.name);
        expect(typeDef.length, 1,
            reason: 'Event "${evt.name}" should have matching type def');
        print('  event "${evt.name}" has matching type def');
      }
    });
  });

  // ============================================================
  // Group 6: Error Code Parsing
  // ============================================================
  group('6. Error codes', () {
    test('test_errors: 7 errors with explicit numbering and gaps', () {
      final r = _load('quasar_test_errors.idl.json');
      final errors = r.idl.errors ?? [];
      expect(errors.length, 7);

      expect(errors[0].code, 0);
      expect(errors[0].name, 'Hello');
      expect(errors[1].code, 1);
      expect(errors[1].name, 'World');
      // Gap from 1 to 100
      expect(errors[2].code, 100);
      expect(errors[2].name, 'ExplicitNum');
      expect(errors[3].code, 101);
      expect(errors[3].name, 'RequireFailed');
      expect(errors[4].code, 102);
      expect(errors[4].name, 'RequireEqFailed');
      expect(errors[5].code, 103);
      expect(errors[5].name, 'ConstraintCustom');
      expect(errors[6].code, 104);
      expect(errors[6].name, 'AddressCustom');

      print('  Verified error codes: [0,1,100-104]');
    });

    test('test_misc: 3 simple errors', () {
      final r = _load('quasar_test_misc.idl.json');
      final errors = r.idl.errors ?? [];
      expect(errors.length, 3);
      expect(errors[0].code, 0);
      expect(errors[0].name, 'Unauthorized');
      expect(errors[1].code, 1);
      expect(errors[1].name, 'InvalidAddress');
      expect(errors[2].code, 2);
      expect(errors[2].name, 'CustomConstraint');
    });

    test('vault and escrow have no errors', () {
      final vault = _load('quasar_vault.idl.json');
      final escrow = _load('quasar_escrow.idl.json');
      expect(vault.idl.errors ?? [], isEmpty);
      expect(escrow.idl.errors ?? [], isEmpty);
    });
  });

  // ============================================================
  // Group 7: Quasar-Specific Type Parsing
  // ============================================================
  group('7. Quasar type parsing', () {
    test('publicKey type fields', () {
      final r = _load('quasar_escrow.idl.json');
      final escrowType = _type(r.idl, 'Escrow');
      final fields = escrowType.type.fields!;

      // First 4 fields should be publicKey
      for (final name in ['maker', 'mintA', 'mintB', 'makerTaB']) {
        final field = fields.firstWhere((f) => f.name == name);
        expect(field.type.kind, 'publicKey',
            reason: '"$name" should be publicKey');
      }
      print('  4 publicKey fields verified in Escrow type');
    });

    test('dynString type (bounded string)', () {
      final r = _load('quasar_multisig.idl.json');
      final config = _type(r.idl, 'MultisigConfig');
      final labelField =
          config.type.fields!.firstWhere((f) => f.name == 'label');
      expect(labelField.type.kind, 'dynString');
      expect(labelField.type.size, 32);
      print('  label: dynString maxLength=32');
    });

    test('dynVec type (bounded vec)', () {
      final r = _load('quasar_multisig.idl.json');
      final config = _type(r.idl, 'MultisigConfig');
      final signersField =
          config.type.fields!.firstWhere((f) => f.name == 'signers');
      expect(signersField.type.kind, 'dynVec');
      expect(signersField.type.size, 10);
      expect(signersField.type.inner?.kind, 'publicKey');
      print('  signers: dynVec<publicKey, 10>');
    });

    test('tail type (string element)', () {
      final r = _load('quasar_test_misc.idl.json');
      final tailStr = _type(r.idl, 'TailStrAccount');
      final labelField =
          tailStr.type.fields!.firstWhere((f) => f.name == 'label');
      expect(labelField.type.kind, 'tail');
      expect(labelField.type.inner?.kind, 'string');
      print('  label: tail<string>');
    });

    test('tail type (bytes element)', () {
      final r = _load('quasar_test_misc.idl.json');
      final tailBytes = _type(r.idl, 'TailBytesAccount');
      final dataField =
          tailBytes.type.fields!.firstWhere((f) => f.name == 'data');
      expect(dataField.type.kind, 'tail');
      expect(dataField.type.inner?.kind, 'bytes');
      print('  data: tail<bytes>');
    });

    test('plain string type (no bounded)', () {
      final r = _load('quasar_test_misc.idl.json');
      final dynamic_ = _type(r.idl, 'DynamicAccount');
      final nameField =
          dynamic_.type.fields!.firstWhere((f) => f.name == 'name');
      // Plain "string" should parse as 'string' kind (same as Anchor)
      expect(nameField.type.kind, 'string');
      print('  name: string (plain, not bounded)');
    });

    test('defined type reference', () {
      final r = _load('quasar_test_misc.idl.json');
      final dynamic_ = _type(r.idl, 'DynamicAccount');
      final tagsField =
          dynamic_.type.fields!.firstWhere((f) => f.name == 'tags');
      expect(tagsField.type.kind, 'defined');
      print('  tags: defined(${tagsField.type.defined?.name})');
    });

    test('u128 type in LargeEvent', () {
      final r = _load('quasar_test_events.idl.json');
      final largeEvt = _type(r.idl, 'LargeEvent');
      final gField = largeEvt.type.fields!.firstWhere((f) => f.name == 'g');
      final hField = largeEvt.type.fields!.firstWhere((f) => f.name == 'h');
      expect(gField.type.kind, 'u128');
      expect(hField.type.kind, 'u128');
      print('  g: u128, h: u128');
    });

    test('instruction arg with dynString type', () {
      final r = _load('quasar_multisig.idl.json');
      final ix = _ix(r.idl, 'setLabel');
      final labelArg = ix.args.firstWhere((a) => a.name == 'label');
      expect(labelArg.type.kind, 'dynString');
      expect(labelArg.type.size, 32);
      print('  setLabel(label: dynString<32>)');
    });

    test('instruction arg with publicKey type', () {
      final r = _load('quasar_test_misc.idl.json');
      final ix = _ix(r.idl, 'assignTest');
      final ownerArg = ix.args.firstWhere((a) => a.name == 'owner');
      expect(ownerArg.type.kind, 'publicKey');
      print('  assignTest(owner: publicKey)');
    });
  });

  // ============================================================
  // Group 8: Instruction Account Parsing
  // ============================================================
  group('8. Instruction account parsing', () {
    test('vault deposit: writable/signer flags', () {
      final r = _load('quasar_vault.idl.json');
      final ix = _ix(r.idl, 'deposit');
      expect(ix.accounts.length, 3);

      final user = _ixAcct(ix, 'user');
      expect(user.writable, isTrue);
      expect(user.signer, isTrue);

      final vault = _ixAcct(ix, 'vault');
      expect(vault.writable, isTrue);
      expect(vault.signer, isFalse);

      final sys = _ixAcct(ix, 'systemProgram');
      expect(sys.writable, isFalse);
      expect(sys.signer, isFalse);
      expect(sys.address, '11111111111111111111111111111111');
      print('  deposit: user(W+S), vault(W), systemProgram(addr)');
    });

    test('escrow make: 10 accounts with token program address', () {
      final r = _load('quasar_escrow.idl.json');
      final ix = _ix(r.idl, 'make');
      expect(ix.accounts.length, 10);

      final tokenProg = _ixAcct(ix, 'tokenProgram');
      expect(tokenProg.address,
          'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA');
      print('  make: 10 accounts, tokenProgram address verified');
    });

    test('vault account with fixed address', () {
      final r = _load('quasar_vault.idl.json');
      final ix = _ix(r.idl, 'deposit');
      final sys = _ixAcct(ix, 'systemProgram');
      expect(sys.address, isNotNull);
      expect(sys.address, '11111111111111111111111111111111');
    });

    test('escrow: rent sysvar address', () {
      final r = _load('quasar_escrow.idl.json');
      final ix = _ix(r.idl, 'make');
      final rent = _ixAcct(ix, 'rent');
      expect(rent.address, 'SysvarRent111111111111111111111111111111111');
    });
  });

  // ============================================================
  // Group 9: PDA Seed Parsing
  // ============================================================
  group('9. PDA seed parsing', () {
    test('vault deposit: const "vault" + account seed', () {
      final r = _load('quasar_vault.idl.json');
      final ix = _ix(r.idl, 'deposit');
      final vault = _ixAcct(ix, 'vault');

      expect(vault.pda, isNotNull);
      final seeds = vault.pda!.seeds;
      expect(seeds.length, 2);

      // First seed: const bytes for "vault"
      expect(seeds[0], isA<IdlSeedConst>());
      expect(_seedToString(seeds[0]), 'vault');
      print('  seed[0]: const "vault" = ${(seeds[0] as IdlSeedConst).value}');

      // Second seed: account path "user"
      expect(seeds[1], isA<IdlSeedAccount>());
      expect((seeds[1] as IdlSeedAccount).path, 'user');
      print('  seed[1]: account "user"');
    });

    test('escrow make: const "escrow" + account "maker"', () {
      final r = _load('quasar_escrow.idl.json');
      final ix = _ix(r.idl, 'make');
      final escrowAcct = _ixAcct(ix, 'escrow');

      expect(escrowAcct.pda, isNotNull);
      expect(escrowAcct.pda!.seeds.length, 2);
      expect(_seedToString(escrowAcct.pda!.seeds[0]), 'escrow');
      expect((escrowAcct.pda!.seeds[1] as IdlSeedAccount).path, 'maker');
    });

    test('test_pda initLiteralSeed: single const "config"', () {
      final r = _load('quasar_test_pda.idl.json');
      final ix = _ix(r.idl, 'initLiteralSeed');
      final config = _ixAcct(ix, 'config');

      expect(config.pda!.seeds.length, 1);
      expect(config.pda!.seeds[0], isA<IdlSeedConst>());
      expect(_seedToString(config.pda!.seeds[0]), 'config');
      print('  single literal seed: "config"');
    });

    test('test_pda initMultiSeeds: const + 2 accounts', () {
      final r = _load('quasar_test_pda.idl.json');
      final ix = _ix(r.idl, 'initMultiSeeds');
      final complex = _ixAcct(ix, 'complex');

      expect(complex.pda!.seeds.length, 3);
      expect(_seedToString(complex.pda!.seeds[0]), 'complex');
      expect((complex.pda!.seeds[1] as IdlSeedAccount).path, 'payer');
      expect((complex.pda!.seeds[2] as IdlSeedAccount).path, 'authority');
      print('  3 seeds: const + 2 accounts');
    });

    test('multisig: const "multisig" + account "creator"', () {
      final r = _load('quasar_multisig.idl.json');
      final ix = _ix(r.idl, 'create');
      final config = _ixAcct(ix, 'config');

      expect(config.pda!.seeds.length, 2);
      expect(_seedToString(config.pda!.seeds[0]), 'multisig');
      expect((config.pda!.seeds[1] as IdlSeedAccount).path, 'creator');
    });
  });

  // ============================================================
  // Group 10: hasRemaining Flag
  // ============================================================
  group('10. hasRemaining flag', () {
    test('multisig create: hasRemaining=true', () {
      final r = _load('quasar_multisig.idl.json');
      final ix = _ix(r.idl, 'create');
      expect(ix.hasRemaining, isTrue);
      print('  create hasRemaining=true');
    });

    test('multisig executeTransfer: hasRemaining=true', () {
      final r = _load('quasar_multisig.idl.json');
      final ix = _ix(r.idl, 'executeTransfer');
      expect(ix.hasRemaining, isTrue);
    });

    test('multisig deposit: hasRemaining=false (default)', () {
      final r = _load('quasar_multisig.idl.json');
      final ix = _ix(r.idl, 'deposit');
      expect(ix.hasRemaining, isFalse);
    });

    test('test_misc remainingAccountsCheck: hasRemaining=true', () {
      final r = _load('quasar_test_misc.idl.json');
      final ix = _ix(r.idl, 'remainingAccountsCheck');
      expect(ix.hasRemaining, isTrue);
    });

    test('vault deposit: hasRemaining=false', () {
      final r = _load('quasar_vault.idl.json');
      final ix = _ix(r.idl, 'deposit');
      expect(ix.hasRemaining, isFalse);
    });
  });

  // ============================================================
  // Group 11: Instruction Args
  // ============================================================
  group('11. Instruction args', () {
    test('vault deposit: single u64 arg', () {
      final r = _load('quasar_vault.idl.json');
      final ix = _ix(r.idl, 'deposit');
      expect(ix.args.length, 1);
      expect(ix.args[0].name, 'amount');
      expect(ix.args[0].type.kind, 'u64');
    });

    test('escrow make: two u64 args', () {
      final r = _load('quasar_escrow.idl.json');
      final ix = _ix(r.idl, 'make');
      expect(ix.args.length, 2);
      expect(ix.args[0].name, 'deposit');
      expect(ix.args[0].type.kind, 'u64');
      expect(ix.args[1].name, 'receive');
      expect(ix.args[1].type.kind, 'u64');
    });

    test('escrow take: no args', () {
      final r = _load('quasar_escrow.idl.json');
      final ix = _ix(r.idl, 'take');
      expect(ix.args, isEmpty);
    });

    test('test_misc createAccountTest: mixed types (u64, u64, publicKey)',
        () {
      final r = _load('quasar_test_misc.idl.json');
      final ix = _ix(r.idl, 'createAccountTest');
      expect(ix.args.length, 3);
      expect(ix.args[0].name, 'lamports');
      expect(ix.args[0].type.kind, 'u64');
      expect(ix.args[1].name, 'space');
      expect(ix.args[1].type.kind, 'u64');
      expect(ix.args[2].name, 'owner');
      expect(ix.args[2].type.kind, 'publicKey');
    });

    test('test_events emitLargeEvent: 8 args with u128', () {
      final r = _load('quasar_test_events.idl.json');
      final ix = _ix(r.idl, 'emitLargeEvent');
      expect(ix.args.length, 8);
      // Last two should be u128
      expect(ix.args[6].type.kind, 'u128');
      expect(ix.args[7].type.kind, 'u128');
    });
  });

  // ============================================================
  // Group 12: Type Definition Structure
  // ============================================================
  group('12. Type definition structure', () {
    test('Escrow account type: 6 fields, correct layout', () {
      final r = _load('quasar_escrow.idl.json');
      final t = _type(r.idl, 'Escrow');
      final fields = t.type.fields!;
      expect(fields.length, 6);

      expect(fields[0].name, 'maker');
      expect(fields[0].type.kind, 'publicKey');
      expect(fields[1].name, 'mintA');
      expect(fields[1].type.kind, 'publicKey');
      expect(fields[2].name, 'mintB');
      expect(fields[2].type.kind, 'publicKey');
      expect(fields[3].name, 'makerTaB');
      expect(fields[3].type.kind, 'publicKey');
      expect(fields[4].name, 'receive');
      expect(fields[4].type.kind, 'u64');
      expect(fields[5].name, 'bump');
      expect(fields[5].type.kind, 'u8');

      print('  Escrow: [pubkey*4, u64, u8]');
    });

    test('SimpleAccount: authority(pubkey) + value(u64) + bump(u8)', () {
      final r = _load('quasar_test_misc.idl.json');
      final t = _type(r.idl, 'SimpleAccount');
      final fields = t.type.fields!;
      expect(fields.length, 3);
      expect(fields[0].type.kind, 'publicKey');
      expect(fields[1].type.kind, 'u64');
      expect(fields[2].type.kind, 'u8');
    });

    test('MultisigConfig: mixed fixed + dynamic types', () {
      final r = _load('quasar_multisig.idl.json');
      final t = _type(r.idl, 'MultisigConfig');
      final fields = t.type.fields!;
      expect(fields.length, 5);

      expect(fields[0].name, 'creator');
      expect(fields[0].type.kind, 'publicKey');
      expect(fields[1].name, 'threshold');
      expect(fields[1].type.kind, 'u8');
      expect(fields[2].name, 'bump');
      expect(fields[2].type.kind, 'u8');
      expect(fields[3].name, 'label');
      expect(fields[3].type.kind, 'dynString');
      expect(fields[4].name, 'signers');
      expect(fields[4].type.kind, 'dynVec');
    });

    test('ClockFullSnapshot: temporal types (i64, u64)', () {
      final r = _load('quasar_test_pda.idl.json');
      // This is in the sysvar IDL but test_pda also has complex types.
      // Let's verify ThreeSeedAccount
      final t = _type(r.idl, 'ThreeSeedAccount');
      final fields = t.type.fields!;
      expect(fields.length, 3);
      expect(fields[0].name, 'first');
      expect(fields[0].type.kind, 'publicKey');
      expect(fields[1].name, 'second');
      expect(fields[1].type.kind, 'publicKey');
      expect(fields[2].name, 'bump');
      expect(fields[2].type.kind, 'u8');
    });
  });

  // ============================================================
  // Group 13: IDL Count Verification (structural integrity)
  // ============================================================
  group('13. IDL count verification', () {
    test('vault: 2 ix, 0 accounts, 0 events, 0 types, 0 errors', () {
      final r = _load('quasar_vault.idl.json');
      expect(r.idl.instructions.length, 2);
      expect((r.idl.accounts ?? []).length, 0);
      expect((r.idl.events ?? []).length, 0);
      expect((r.idl.types ?? []).length, 0);
      expect((r.idl.errors ?? []).length, 0);
    });

    test('escrow: 3 ix, 1 account, 3 events, 4 types, 0 errors', () {
      final r = _load('quasar_escrow.idl.json');
      expect(r.idl.instructions.length, 3);
      expect((r.idl.accounts ?? []).length, 1);
      expect((r.idl.events ?? []).length, 3);
      expect((r.idl.types ?? []).length, 4);
      expect((r.idl.errors ?? []).length, 0);
    });

    test('test_misc: 33 ix, 7 accounts, 0 events, 7 types, 3 errors', () {
      final r = _load('quasar_test_misc.idl.json');
      expect(r.idl.instructions.length, 33);
      expect((r.idl.accounts ?? []).length, 7);
      expect((r.idl.events ?? []).length, 0);
      expect((r.idl.types ?? []).length, 7);
      expect((r.idl.errors ?? []).length, 3);
    });

    test('test_events: 8 ix, 0 accounts, 7 events, 7 types, 0 errors', () {
      final r = _load('quasar_test_events.idl.json');
      expect(r.idl.instructions.length, 8);
      expect((r.idl.accounts ?? []).length, 0);
      expect((r.idl.events ?? []).length, 7);
      expect((r.idl.types ?? []).length, 7);
      expect((r.idl.errors ?? []).length, 0);
    });

    test('test_pda: 10 ix, 7 accounts, 0 events, 7 types, 0 errors', () {
      final r = _load('quasar_test_pda.idl.json');
      expect(r.idl.instructions.length, 10);
      expect((r.idl.accounts ?? []).length, 7);
      expect((r.idl.events ?? []).length, 0);
      expect((r.idl.types ?? []).length, 7);
      expect((r.idl.errors ?? []).length, 0);
    });

    test('test_errors: 28 ix, 1 account, 0 events, 1 type, 7 errors', () {
      final r = _load('quasar_test_errors.idl.json');
      expect(r.idl.instructions.length, 28);
      expect((r.idl.accounts ?? []).length, 1);
      expect((r.idl.events ?? []).length, 0);
      expect((r.idl.types ?? []).length, 1);
      expect((r.idl.errors ?? []).length, 7);
    });

    test('multisig: 4 ix, 1 account, 0 events, 1 type, 0 errors', () {
      final r = _load('quasar_multisig.idl.json');
      expect(r.idl.instructions.length, 4);
      expect((r.idl.accounts ?? []).length, 1);
      expect((r.idl.events ?? []).length, 0);
      expect((r.idl.types ?? []).length, 1);
      expect((r.idl.errors ?? []).length, 0);
    });
  });

  // ============================================================
  // Group 14: DiscriminatorComputer Integration
  // ============================================================
  group('14. DiscriminatorComputer integration', () {
    test('isExplicit for Quasar short discriminators', () {
      expect(DiscriminatorComputer.isExplicit([0]), isTrue);
      expect(DiscriminatorComputer.isExplicit([1]), isTrue);
      expect(DiscriminatorComputer.isExplicit([1, 2]), isTrue);
      expect(DiscriminatorComputer.isExplicit([0, 1, 2, 3]), isTrue);
      // 8-byte discriminator should NOT be explicit (that's Anchor)
      expect(
          DiscriminatorComputer.isExplicit([0, 1, 2, 3, 4, 5, 6, 7]), isFalse);
      print('  1-4 byte discs are explicit, 8-byte is not');
    });

    test('fromExplicit creates correct Uint8List', () {
      final disc = DiscriminatorComputer.fromExplicit([42]);
      expect(disc, isA<Uint8List>());
      expect(disc.length, 1);
      expect(disc[0], 42);

      final multi = DiscriminatorComputer.fromExplicit([1, 2]);
      expect(multi.length, 2);
      expect(multi[0], 1);
      expect(multi[1], 2);
    });

    test('compareDiscriminators: same length match', () {
      expect(
        DiscriminatorComputer.compareDiscriminators(
            Uint8List.fromList([0]), Uint8List.fromList([0])),
        isTrue,
      );
      expect(
        DiscriminatorComputer.compareDiscriminators(
            Uint8List.fromList([1, 2]), Uint8List.fromList([1, 2])),
        isTrue,
      );
    });

    test('compareDiscriminators: different length mismatch', () {
      expect(
        DiscriminatorComputer.compareDiscriminators(
            Uint8List.fromList([0]), Uint8List.fromList([0, 1])),
        isFalse,
      );
    });

    test('compareDiscriminators: same length content mismatch', () {
      expect(
        DiscriminatorComputer.compareDiscriminators(
            Uint8List.fromList([0]), Uint8List.fromList([1])),
        isFalse,
      );
    });

    test('resolve() with explicit list returns it directly', () {
      final resolved = DiscriminatorComputer.resolve(
        prefix: 'global',
        name: 'deposit',
        explicit: [42],
      );
      expect(resolved, [42]);
      expect(resolved.length, 1);
    });

    test('resolve() without explicit falls back to SHA256', () {
      final resolved = DiscriminatorComputer.resolve(
        prefix: 'global',
        name: 'deposit',
        explicit: null,
      );
      expect(resolved.length, 8, reason: 'SHA256 discriminator is 8 bytes');
    });
  });

  // ============================================================
  // Group 15: AccountsCoderFactory Dispatch
  // ============================================================
  group('15. AccountsCoderFactory dispatch', () {
    test('Quasar IDL creates ZeroCopyAccountsCoder', () {
      final r = _load('quasar_escrow.idl.json');
      final coder = AccountsCoderFactory.create(r.idl);
      expect(coder, isA<ZeroCopyAccountsCoder>());
      print('  Quasar → ZeroCopyAccountsCoder');
    });

    test('all Quasar IDLs create ZeroCopyAccountsCoder', () {
      final fixtures = [
        'quasar_vault.idl.json',
        'quasar_escrow.idl.json',
        'quasar_test_misc.idl.json',
        'quasar_multisig.idl.json',
      ];
      for (final f in fixtures) {
        final r = _load(f);
        final coder = AccountsCoderFactory.create(r.idl);
        expect(coder, isA<ZeroCopyAccountsCoder>(),
            reason: '$f should use ZeroCopyAccountsCoder');
      }
    });
  });

  // ============================================================
  // Group 16: Zero-Copy Account Encoding / Decoding
  // ============================================================
  group('16. Zero-copy encoding/decoding', () {
    test('Escrow round-trip: encode → decode', () async {
      final r = _load('quasar_escrow.idl.json');
      final coder = ZeroCopyAccountsCoder(r.idl);

      // Build a fake Escrow account data
      final maker = List.filled(32, 0x01);
      final mintA = List.filled(32, 0x02);
      final mintB = List.filled(32, 0x03);
      final makerTaB = List.filled(32, 0x04);

      final escrowData = <String, dynamic>{
        'maker': Uint8List.fromList(maker),
        'mintA': Uint8List.fromList(mintA),
        'mintB': Uint8List.fromList(mintB),
        'makerTaB': Uint8List.fromList(makerTaB),
        'receive': BigInt.from(1000000),
        'bump': 254,
      };

      final encoded = await coder.encode('Escrow', escrowData);
      print('  encoded length: ${encoded.length}');

      // Discriminator [1] + 32*4 + 8 + 1 = 1 + 128 + 8 + 1 = 138
      expect(encoded.length, 138);
      // First byte should be discriminator [1]
      expect(encoded[0], 1);

      final decoded = coder.decode('Escrow', encoded);
      expect(decoded['receive'], BigInt.from(1000000));
      expect(decoded['bump'], 254);
      print('  decoded receive=${decoded['receive']} bump=${decoded['bump']}');

      // Verify pubkeys round-trip
      expect(
        (decoded['maker'] as Uint8List).toList(),
        maker,
      );
    });

    test('SimpleAccount round-trip: pubkey + u64 + u8', () async {
      final r = _load('quasar_test_misc.idl.json');
      final coder = ZeroCopyAccountsCoder(r.idl);

      final data = <String, dynamic>{
        'authority': Uint8List.fromList(List.filled(32, 0xAA)),
        'value': BigInt.from(42),
        'bump': 255,
      };

      final encoded = await coder.encode('SimpleAccount', data);
      // disc [1] + 32 + 8 + 1 = 42
      expect(encoded.length, 42);
      expect(encoded[0], 1);

      final decoded = coder.decode('SimpleAccount', encoded);
      expect(decoded['value'], BigInt.from(42));
      expect(decoded['bump'], 255);
      print('  SimpleAccount round-trip OK');
    });

    test('MultiDiscAccount: 2-byte discriminator', () async {
      final r = _load('quasar_test_misc.idl.json');
      final coder = ZeroCopyAccountsCoder(r.idl);

      final data = <String, dynamic>{
        'data': BigInt.from(99),
      };

      final encoded = await coder.encode('MultiDiscAccount', data);
      // disc [1,2] + 8 = 10
      expect(encoded.length, 10);
      expect(encoded[0], 1);
      expect(encoded[1], 2);

      final decoded = coder.decode('MultiDiscAccount', encoded);
      expect(decoded['data'], BigInt.from(99));
      print('  MultiDiscAccount 2-byte disc round-trip OK');
    });

    test('MultisigConfig: dynString + dynVec round-trip', () async {
      final r = _load('quasar_multisig.idl.json');
      final coder = ZeroCopyAccountsCoder(r.idl);

      final signer1 = Uint8List.fromList(List.filled(32, 0x11));
      final signer2 = Uint8List.fromList(List.filled(32, 0x22));

      final data = <String, dynamic>{
        'creator': Uint8List.fromList(List.filled(32, 0xFF)),
        'threshold': 2,
        'bump': 253,
        'label': 'test-ms',
        'signers': [signer1, signer2],
      };

      final encoded = await coder.encode('MultisigConfig', data);
      print('  MultisigConfig encoded length: ${encoded.length}');

      // disc [1] + pubkey(32) + u8 + u8 + dynString(4+7) + dynVec(4+32*2)
      // = 1 + 32 + 1 + 1 + 11 + 68 = 114
      expect(encoded.length, 114);
      expect(encoded[0], 1); // disc

      final decoded = coder.decode('MultisigConfig', encoded);
      expect(decoded['threshold'], 2);
      expect(decoded['bump'], 253);
      expect(decoded['label'], 'test-ms');
      final decodedSigners = decoded['signers'] as List;
      expect(decodedSigners.length, 2);
      expect((decodedSigners[0] as Uint8List).toList(), signer1.toList());
      print('  MultisigConfig round-trip OK');
    });
  });

  // ============================================================
  // Group 17: Instruction Encoding
  // ============================================================
  group('17. Instruction encoding', () {
    test('vault deposit: disc [0] + u64', () {
      final r = _load('quasar_vault.idl.json');
      final coder = BorshInstructionCoder(r.idl);

      final encoded = coder.encode('deposit', {'amount': BigInt.from(5000)});
      print('  deposit encoded: ${bytesToHex(encoded)}');

      // disc [0] + u64(8) = 9 bytes
      expect(encoded.length, 9);
      expect(encoded[0], 0);
    });

    test('vault withdraw: disc [1] + u64', () {
      final r = _load('quasar_vault.idl.json');
      final coder = BorshInstructionCoder(r.idl);

      final encoded = coder.encode('withdraw', {'amount': BigInt.from(100)});
      expect(encoded.length, 9);
      expect(encoded[0], 1);
    });

    test('escrow make: disc [0] + 2*u64', () {
      final r = _load('quasar_escrow.idl.json');
      final coder = BorshInstructionCoder(r.idl);

      final encoded = coder.encode('make', {
        'deposit': BigInt.from(1000),
        'receive': BigInt.from(2000),
      });
      // disc [0] + u64(8) + u64(8) = 17
      expect(encoded.length, 17);
      expect(encoded[0], 0);
    });

    test('escrow take: disc [1], no args', () {
      final r = _load('quasar_escrow.idl.json');
      final coder = BorshInstructionCoder(r.idl);

      final encoded = coder.encode('take', {});
      // disc [1] only
      expect(encoded.length, 1);
      expect(encoded[0], 1);
    });

    test('test_misc doubleMutCheck: disc [41], no args', () {
      final r = _load('quasar_test_misc.idl.json');
      final coder = BorshInstructionCoder(r.idl);

      final encoded = coder.encode('doubleMutCheck', {});
      expect(encoded.length, 1);
      expect(encoded[0], 41);
      print('  doubleMutCheck encoded: disc=[41]');
    });

    test('test_misc assignTest: disc [10] + publicKey arg', () {
      final r = _load('quasar_test_misc.idl.json');
      final coder = BorshInstructionCoder(r.idl);

      final ownerPubkey = Uint8List.fromList(List.filled(32, 0xBB));
      final encoded = coder.encode('assignTest', {'owner': ownerPubkey});
      // disc [10] + 32 bytes pubkey = 33
      expect(encoded.length, 33);
      expect(encoded[0], 10);
      print('  assignTest encoded length=${encoded.length}');
    });

    test('instruction decode round-trip', () {
      final r = _load('quasar_vault.idl.json');
      final coder = BorshInstructionCoder(r.idl);

      final encoded = coder.encode('deposit', {'amount': BigInt.from(7777)});
      final decoded = coder.decode(encoded);
      expect(decoded, isNotNull);
      expect(decoded!.name, 'deposit');
      // BorshInstructionCoder may return int or BigInt depending on size
      final amountValue = decoded.data['amount'];
      expect(
        amountValue == BigInt.from(7777) || amountValue == 7777,
        isTrue,
        reason: 'amount should be 7777 (got $amountValue, type=${amountValue.runtimeType})',
      );
      print('  deposit decode: name=${decoded.name} amount=$amountValue (${amountValue.runtimeType})');
    });
  });

  // ============================================================
  // Group 18: IDL JSON Round-Trip (fromJson → toJson → fromJson)
  // ============================================================
  group('18. IDL JSON round-trip', () {
    final fixtures = [
      'quasar_vault.idl.json',
      'quasar_escrow.idl.json',
      'quasar_test_misc.idl.json',
      'quasar_multisig.idl.json',
    ];

    for (final f in fixtures) {
      test('$f round-trips through toJson/fromJson', () {
        final r = _load(f);

        // Serialize back to JSON
        final reJson = r.idl.toJson();

        // Re-parse
        final idl2 = Idl.fromJson(reJson);

        // Structural equality checks
        expect(idl2.instructions.length, r.idl.instructions.length);
        expect(
            (idl2.accounts ?? []).length, (r.idl.accounts ?? []).length);
        expect((idl2.events ?? []).length, (r.idl.events ?? []).length);
        expect((idl2.types ?? []).length, (r.idl.types ?? []).length);
        expect((idl2.errors ?? []).length, (r.idl.errors ?? []).length);

        // Verify instruction names preserved
        for (var i = 0; i < r.idl.instructions.length; i++) {
          expect(idl2.instructions[i].name, r.idl.instructions[i].name);
          expect(idl2.instructions[i].discriminator,
              r.idl.instructions[i].discriminator);
        }

        // Verify format is still Quasar
        expect(idl2.format, IdlFormat.quasar);
        print('  $f round-trip OK');
      });
    }
  });

  // ============================================================
  // Group 19: Event Type Field Verification
  // ============================================================
  group('19. Event type field verification', () {
    test('LargeEvent: 8 fields with u128', () {
      final r = _load('quasar_test_events.idl.json');
      final t = _type(r.idl, 'LargeEvent');
      final fields = t.type.fields!;
      expect(fields.length, 8);

      // Fields a-d are u64
      for (final name in ['a', 'b', 'c', 'd']) {
        expect(fields.firstWhere((f) => f.name == name).type.kind, 'u64');
      }
      // Fields e,f are pubkey
      for (final name in ['e', 'f']) {
        expect(
            fields.firstWhere((f) => f.name == name).type.kind, 'publicKey');
      }
      // Fields g,h are u128
      for (final name in ['g', 'h']) {
        expect(fields.firstWhere((f) => f.name == name).type.kind, 'u128');
      }
      print('  LargeEvent: [u64*4, pubkey*2, u128*2]');
    });

    test('MakeEvent: 6 fields', () {
      final r = _load('quasar_escrow.idl.json');
      final t = _type(r.idl, 'MakeEvent');
      final fields = t.type.fields!;
      expect(fields.length, 6);
      expect(fields[0].name, 'escrow');
      expect(fields[0].type.kind, 'publicKey');
      expect(fields[4].name, 'deposit');
      expect(fields[4].type.kind, 'u64');
    });

    test('EmptyEvent (BoolEvent): has a single bool field', () {
      final r = _load('quasar_test_events.idl.json');
      final t = _type(r.idl, 'BoolEvent');
      final fields = t.type.fields!;
      expect(fields.length, 1);
      expect(fields[0].name, 'flag');
      expect(fields[0].type.kind, 'bool');
    });
  });

  // ============================================================
  // Group 20: Verification Report (summary)
  // ============================================================
  group('20. Verification report (summary)', () {
    test('generate phase 3 verification report', () {
      final report = VerificationReport();

      // Test all 7 IDLs parse
      final fixtures = [
        'quasar_vault.idl.json',
        'quasar_escrow.idl.json',
        'quasar_test_misc.idl.json',
        'quasar_test_events.idl.json',
        'quasar_test_pda.idl.json',
        'quasar_test_errors.idl.json',
        'quasar_multisig.idl.json',
      ];

      for (final f in fixtures) {
        try {
          final json = loadFixtureJson(f);
          final format = IdlFormat.detect(json);
          final idl = Idl.fromJson(json);
          if (format == IdlFormat.quasar && idl.instructions.isNotEmpty) {
            report.pass('Quasar', 'Parse $f');
          } else {
            report.fail('Quasar', 'Parse $f',
                error: 'format=$format ix=${idl.instructions.length}');
          }
        } catch (e) {
          report.fail('Quasar', 'Parse $f', error: '$e');
        }
      }

      // Test ZeroCopy coder creation
      for (final f in fixtures) {
        try {
          final idl = loadFixtureIdl(f);
          AccountsCoderFactory.create(idl);
          report.pass('Quasar', 'ZeroCopyCoder $f');
        } catch (e) {
          report.fail('Quasar', 'ZeroCopyCoder $f', error: '$e');
        }
      }

      // Test instruction coder creation
      for (final f in fixtures) {
        try {
          final idl = loadFixtureIdl(f);
          BorshInstructionCoder(idl);
          report.pass('Quasar', 'InstructionCoder $f');
        } catch (e) {
          report.fail('Quasar', 'InstructionCoder $f', error: '$e');
        }
      }

      report.printSummary();
      expect(report.failCount, 0);
    });
  });
}
