/// Cross-reference verification: Dart SDK output vs TypeScript Anchor SDK truth values.
///
/// This test loads `test/reference/references.json` (generated by the TS Anchor SDK)
/// and verifies that the Dart SDK computes identical:
///   - Instruction discriminators (SHA256 of "global:" + snake_case_name)
///   - Account discriminators (SHA256 of "account:" + name)
///   - Event discriminators (SHA256 of "event:" + name)
///   - Encoded instruction bytes (discriminator + Borsh-serialized args)
///   - Standalone discriminator computations
///   - Borsh primitive encoding (u8, u16, u32, u64, i8, i16, i32, i64, bool, string)
///
/// This is the ground-truth test: if the Dart SDK produces different bytes than
/// the TypeScript SDK for the same inputs, the Dart SDK is wrong.
library;

import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';

import 'package:coral_xyz/src/coder/borsh_types.dart';
import 'package:coral_xyz/src/coder/discriminator_computer.dart';
import 'package:coral_xyz/src/coder/instruction_coder.dart';
import 'package:coral_xyz/src/idl/idl.dart';
import 'package:test/test.dart';

import 'verification_helpers.dart';

/// Load the TS-generated reference JSON.
Map<String, dynamic> _loadReferences() {
  final file = File('test/reference/references.json');
  return jsonDecode(file.readAsStringSync()) as Map<String, dynamic>;
}

/// Load an IDL from the reference test fixtures.
Idl _loadReferenceIdl(String programName) {
  // Map program names to their IDL filenames
  const idlFiles = {
    'basic_counter': 'basic_counter_idl.json',
    'clever_todo': 'todo_idl.json',
    'flutter_vote': 'voting_idl.json',
  };
  final filename = idlFiles[programName];
  if (filename == null) {
    throw StateError('No IDL file mapping for program: $programName');
  }
  final file = File('test/reference/$filename');
  final json = jsonDecode(file.readAsStringSync()) as Map<String, dynamic>;
  return Idl.fromJson(json);
}

/// Convert a JSON list of ints to Uint8List.
Uint8List _jsonBytesToUint8List(List<dynamic> jsonBytes) {
  return Uint8List.fromList(jsonBytes.cast<int>());
}

void main() {
  late Map<String, dynamic> refs;
  late VerificationReport report;

  setUpAll(() {
    refs = _loadReferences();
    report = VerificationReport();
  });

  tearDownAll(() {
    report.printSummary();
  });

  // ===========================================================================
  // Section 1: Per-program discriminator verification
  // ===========================================================================
  group('Per-program instruction discriminators match TS', () {
    test('basic_counter instructions', () {
      final programRefs =
          refs['programs']['basic_counter'] as Map<String, dynamic>;
      final ixRefs = programRefs['instructions'] as Map<String, dynamic>;

      for (final entry in ixRefs.entries) {
        final ixName = entry.key;
        final ixData = entry.value as Map<String, dynamic>;
        final expectedBytes = _jsonBytesToUint8List(
          ixData['discriminator'] as List,
        );
        final preimage = ixData['preimage'] as String;

        // Dart SDK computes discriminator from the preimage prefix + snake_case name
        // The preimage is "global:snake_case_name"
        final dartDiscriminator =
            DiscriminatorComputer.computeInstructionDiscriminator(
              preimage.replaceFirst('global:', ''),
            );

        expect(
          dartDiscriminator,
          equals(expectedBytes),
          reason:
              'Instruction "$ixName" discriminator mismatch. '
              'Preimage: $preimage',
        );
        report.pass(
          'Anchor',
          'basic_counter.$ixName discriminator',
          detail: 'matches TS: ${ixData["discriminatorHex"]}',
        );
      }
    });

    test('clever_todo instructions', () {
      final programRefs =
          refs['programs']['clever_todo'] as Map<String, dynamic>;
      final ixRefs = programRefs['instructions'] as Map<String, dynamic>;

      for (final entry in ixRefs.entries) {
        final ixName = entry.key;
        final ixData = entry.value as Map<String, dynamic>;
        final expectedBytes = _jsonBytesToUint8List(
          ixData['discriminator'] as List,
        );
        final preimage = ixData['preimage'] as String;

        final dartDiscriminator =
            DiscriminatorComputer.computeInstructionDiscriminator(
              preimage.replaceFirst('global:', ''),
            );

        expect(
          dartDiscriminator,
          equals(expectedBytes),
          reason:
              'Instruction "$ixName" discriminator mismatch. '
              'Preimage: $preimage',
        );
        report.pass(
          'Anchor',
          'clever_todo.$ixName discriminator',
          detail: 'matches TS: ${ixData["discriminatorHex"]}',
        );
      }
    });

    test('flutter_vote instructions', () {
      final programRefs =
          refs['programs']['flutter_vote'] as Map<String, dynamic>;
      final ixRefs = programRefs['instructions'] as Map<String, dynamic>;

      for (final entry in ixRefs.entries) {
        final ixName = entry.key;
        final ixData = entry.value as Map<String, dynamic>;
        final expectedBytes = _jsonBytesToUint8List(
          ixData['discriminator'] as List,
        );
        final preimage = ixData['preimage'] as String;

        final dartDiscriminator =
            DiscriminatorComputer.computeInstructionDiscriminator(
              preimage.replaceFirst('global:', ''),
            );

        expect(
          dartDiscriminator,
          equals(expectedBytes),
          reason:
              'Instruction "$ixName" discriminator mismatch. '
              'Preimage: $preimage',
        );
        report.pass(
          'Anchor',
          'flutter_vote.$ixName discriminator',
          detail: 'matches TS: ${ixData["discriminatorHex"]}',
        );
      }
    });
  });

  group('Per-program account discriminators match TS', () {
    test('basic_counter accounts', () {
      final programRefs =
          refs['programs']['basic_counter'] as Map<String, dynamic>;
      final accRefs = programRefs['accounts'] as Map<String, dynamic>;

      for (final entry in accRefs.entries) {
        final accName = entry.key;
        final accData = entry.value as Map<String, dynamic>;
        final expectedBytes = _jsonBytesToUint8List(
          accData['discriminator'] as List,
        );

        final dartDiscriminator =
            DiscriminatorComputer.computeAccountDiscriminator(accName);

        expect(
          dartDiscriminator,
          equals(expectedBytes),
          reason: 'Account "$accName" discriminator mismatch',
        );
        report.pass(
          'Anchor',
          'basic_counter.$accName account discriminator',
          detail: 'matches TS: ${accData["discriminatorHex"]}',
        );
      }
    });

    test('clever_todo accounts', () {
      final programRefs =
          refs['programs']['clever_todo'] as Map<String, dynamic>;
      final accRefs = programRefs['accounts'] as Map<String, dynamic>;

      for (final entry in accRefs.entries) {
        final accName = entry.key;
        final accData = entry.value as Map<String, dynamic>;
        final expectedBytes = _jsonBytesToUint8List(
          accData['discriminator'] as List,
        );

        final dartDiscriminator =
            DiscriminatorComputer.computeAccountDiscriminator(accName);

        expect(
          dartDiscriminator,
          equals(expectedBytes),
          reason: 'Account "$accName" discriminator mismatch',
        );
        report.pass(
          'Anchor',
          'clever_todo.$accName account discriminator',
          detail: 'matches TS: ${accData["discriminatorHex"]}',
        );
      }
    });

    test('flutter_vote accounts', () {
      final programRefs =
          refs['programs']['flutter_vote'] as Map<String, dynamic>;
      final accRefs = programRefs['accounts'] as Map<String, dynamic>;

      for (final entry in accRefs.entries) {
        final accName = entry.key;
        final accData = entry.value as Map<String, dynamic>;
        final expectedBytes = _jsonBytesToUint8List(
          accData['discriminator'] as List,
        );

        final dartDiscriminator =
            DiscriminatorComputer.computeAccountDiscriminator(accName);

        expect(
          dartDiscriminator,
          equals(expectedBytes),
          reason: 'Account "$accName" discriminator mismatch',
        );
        report.pass(
          'Anchor',
          'flutter_vote.$accName account discriminator',
          detail: 'matches TS: ${accData["discriminatorHex"]}',
        );
      }
    });
  });

  // ===========================================================================
  // Section 2: Instruction encoding — full byte comparison against TS
  // ===========================================================================
  group('Instruction encoding matches TS byte-for-byte', () {
    test('basic_counter encoded instructions', () {
      final idl = _loadReferenceIdl('basic_counter');
      final coder = BorshInstructionCoder(idl);
      final programRefs =
          refs['programs']['basic_counter'] as Map<String, dynamic>;
      final encodedIxs = programRefs['encodedInstructions'] as List;

      for (final ixRef in encodedIxs) {
        final ixName = ixRef['instruction'] as String;
        final args = Map<String, dynamic>.from(ixRef['args'] as Map);
        final expectedBytes = _jsonBytesToUint8List(ixRef['bytes'] as List);
        final expectedHex = ixRef['hex'] as String;

        // Convert string amounts to BigInt for u64 fields
        final convertedArgs = _convertArgsForEncoding(args, idl, ixName);

        final dartBytes = coder.encode(ixName, convertedArgs);

        expect(
          dartBytes,
          equals(expectedBytes),
          reason:
              'basic_counter.$ixName encoding mismatch.\n'
              '  Dart hex: ${bytesToHex(dartBytes)}\n'
              '  TS hex:   $expectedHex',
        );
        report.pass(
          'Anchor',
          'basic_counter.$ixName encode',
          detail: 'bytes match TS: $expectedHex',
        );
      }
    });

    test('clever_todo encoded instructions', () {
      final idl = _loadReferenceIdl('clever_todo');
      final coder = BorshInstructionCoder(idl);
      final programRefs =
          refs['programs']['clever_todo'] as Map<String, dynamic>;
      final encodedIxs = programRefs['encodedInstructions'] as List;

      for (final ixRef in encodedIxs) {
        final ixName = ixRef['instruction'] as String;
        final args = Map<String, dynamic>.from(ixRef['args'] as Map);
        final expectedBytes = _jsonBytesToUint8List(ixRef['bytes'] as List);
        final expectedHex = ixRef['hex'] as String;

        final convertedArgs = _convertArgsForEncoding(args, idl, ixName);

        final dartBytes = coder.encode(ixName, convertedArgs);

        expect(
          dartBytes,
          equals(expectedBytes),
          reason:
              'clever_todo.$ixName encoding mismatch.\n'
              '  Dart hex: ${bytesToHex(dartBytes)}\n'
              '  TS hex:   $expectedHex',
        );
        report.pass(
          'Anchor',
          'clever_todo.$ixName encode',
          detail: 'bytes match TS: $expectedHex',
        );
      }
    });

    test('flutter_vote encoded instructions', () {
      final idl = _loadReferenceIdl('flutter_vote');
      final coder = BorshInstructionCoder(idl);
      final programRefs =
          refs['programs']['flutter_vote'] as Map<String, dynamic>;
      final encodedIxs = programRefs['encodedInstructions'] as List;

      for (final ixRef in encodedIxs) {
        final ixName = ixRef['instruction'] as String;
        final args = Map<String, dynamic>.from(ixRef['args'] as Map);
        final expectedBytes = _jsonBytesToUint8List(ixRef['bytes'] as List);
        final expectedHex = ixRef['hex'] as String;

        final convertedArgs = _convertArgsForEncoding(args, idl, ixName);

        final dartBytes = coder.encode(ixName, convertedArgs);

        expect(
          dartBytes,
          equals(expectedBytes),
          reason:
              'flutter_vote.$ixName encoding mismatch.\n'
              '  Dart hex: ${bytesToHex(dartBytes)}\n'
              '  TS hex:   $expectedHex',
        );
        report.pass(
          'Anchor',
          'flutter_vote.$ixName encode',
          detail: 'bytes match TS: $expectedHex',
        );
      }
    });
  });

  // ===========================================================================
  // Section 3: Standalone discriminator verification
  // ===========================================================================
  group('Standalone discriminators match TS', () {
    test('instruction discriminators', () {
      final standaloneRefs =
          refs['standaloneDiscriminators'] as Map<String, dynamic>;
      final ixRefs = standaloneRefs['instructions'] as Map<String, dynamic>;

      for (final entry in ixRefs.entries) {
        final name = entry.key;
        final data = entry.value as Map<String, dynamic>;
        final expectedBytes = _jsonBytesToUint8List(
          data['discriminator'] as List,
        );
        final preimage = data['preimage'] as String;

        final dartDiscriminator =
            DiscriminatorComputer.computeInstructionDiscriminator(
              preimage.replaceFirst('global:', ''),
            );

        expect(
          dartDiscriminator,
          equals(expectedBytes),
          reason: 'Standalone instruction "$name" discriminator mismatch',
        );
        report.pass(
          'Anchor',
          'standalone instruction disc: $name',
          detail: 'hex: ${data["hex"]}',
        );
      }
    });

    test('account discriminators', () {
      final standaloneRefs =
          refs['standaloneDiscriminators'] as Map<String, dynamic>;
      final accRefs = standaloneRefs['accounts'] as Map<String, dynamic>;

      for (final entry in accRefs.entries) {
        final name = entry.key;
        final data = entry.value as Map<String, dynamic>;
        final expectedBytes = _jsonBytesToUint8List(
          data['discriminator'] as List,
        );

        final dartDiscriminator =
            DiscriminatorComputer.computeAccountDiscriminator(name);

        expect(
          dartDiscriminator,
          equals(expectedBytes),
          reason: 'Standalone account "$name" discriminator mismatch',
        );
        report.pass(
          'Anchor',
          'standalone account disc: $name',
          detail: 'hex: ${data["hex"]}',
        );
      }
    });

    test('event discriminators', () {
      final standaloneRefs =
          refs['standaloneDiscriminators'] as Map<String, dynamic>;
      final evtRefs = standaloneRefs['events'] as Map<String, dynamic>;

      for (final entry in evtRefs.entries) {
        final name = entry.key;
        final data = entry.value as Map<String, dynamic>;
        final expectedBytes = _jsonBytesToUint8List(
          data['discriminator'] as List,
        );

        final dartDiscriminator =
            DiscriminatorComputer.computeEventDiscriminator(name);

        expect(
          dartDiscriminator,
          equals(expectedBytes),
          reason: 'Standalone event "$name" discriminator mismatch',
        );
        report.pass(
          'Anchor',
          'standalone event disc: $name',
          detail: 'hex: ${data["hex"]}',
        );
      }
    });
  });

  // ===========================================================================
  // Section 4: Borsh primitive encoding verification
  // ===========================================================================
  group('Borsh encoding matches TS', () {
    test('unsigned integers', () {
      final borshRefs = refs['borshEncoding'] as Map<String, dynamic>;

      // u8
      final u8Ref = borshRefs['u8'] as Map<String, dynamic>;
      final u8Expected = _jsonBytesToUint8List(u8Ref['bytes'] as List);
      final u8Dart = _encodePrimitive('u8', u8Ref['value']);
      expect(u8Dart, equals(u8Expected), reason: 'u8 encoding mismatch');
      report.pass(
        'Borsh',
        'u8 encoding',
        detail: 'value=${u8Ref["value"]}, hex=${u8Ref["hex"]}',
      );

      // u16
      final u16Ref = borshRefs['u16'] as Map<String, dynamic>;
      final u16Expected = _jsonBytesToUint8List(u16Ref['bytes'] as List);
      final u16Dart = _encodePrimitive('u16', u16Ref['value']);
      expect(u16Dart, equals(u16Expected), reason: 'u16 encoding mismatch');
      report.pass(
        'Borsh',
        'u16 encoding',
        detail: 'value=${u16Ref["value"]}, hex=${u16Ref["hex"]}',
      );

      // u32
      final u32Ref = borshRefs['u32'] as Map<String, dynamic>;
      final u32Expected = _jsonBytesToUint8List(u32Ref['bytes'] as List);
      final u32Dart = _encodePrimitive('u32', u32Ref['value']);
      expect(u32Dart, equals(u32Expected), reason: 'u32 encoding mismatch');
      report.pass(
        'Borsh',
        'u32 encoding',
        detail: 'value=${u32Ref["value"]}, hex=${u32Ref["hex"]}',
      );

      // u64
      final u64Ref = borshRefs['u64'] as Map<String, dynamic>;
      final u64Expected = _jsonBytesToUint8List(u64Ref['bytes'] as List);
      final u64Dart = _encodePrimitive('u64', u64Ref['value']);
      expect(u64Dart, equals(u64Expected), reason: 'u64 encoding mismatch');
      report.pass(
        'Borsh',
        'u64 encoding',
        detail: 'value=${u64Ref["value"]}, hex=${u64Ref["hex"]}',
      );
    });

    test('signed integers', () {
      final borshRefs = refs['borshEncoding'] as Map<String, dynamic>;

      // i8
      final i8Ref = borshRefs['i8'] as Map<String, dynamic>;
      final i8Expected = _jsonBytesToUint8List(i8Ref['bytes'] as List);
      final i8Dart = _encodePrimitive('i8', i8Ref['value']);
      expect(i8Dart, equals(i8Expected), reason: 'i8 encoding mismatch');
      report.pass(
        'Borsh',
        'i8 encoding',
        detail: 'value=${i8Ref["value"]}, hex=${i8Ref["hex"]}',
      );

      // i16
      final i16Ref = borshRefs['i16'] as Map<String, dynamic>;
      final i16Expected = _jsonBytesToUint8List(i16Ref['bytes'] as List);
      final i16Dart = _encodePrimitive('i16', i16Ref['value']);
      expect(i16Dart, equals(i16Expected), reason: 'i16 encoding mismatch');
      report.pass(
        'Borsh',
        'i16 encoding',
        detail: 'value=${i16Ref["value"]}, hex=${i16Ref["hex"]}',
      );

      // i32
      final i32Ref = borshRefs['i32'] as Map<String, dynamic>;
      final i32Expected = _jsonBytesToUint8List(i32Ref['bytes'] as List);
      final i32Dart = _encodePrimitive('i32', i32Ref['value']);
      expect(i32Dart, equals(i32Expected), reason: 'i32 encoding mismatch');
      report.pass(
        'Borsh',
        'i32 encoding',
        detail: 'value=${i32Ref["value"]}, hex=${i32Ref["hex"]}',
      );

      // i64
      final i64Ref = borshRefs['i64'] as Map<String, dynamic>;
      final i64Expected = _jsonBytesToUint8List(i64Ref['bytes'] as List);
      final i64Dart = _encodePrimitive('i64', i64Ref['value']);
      expect(i64Dart, equals(i64Expected), reason: 'i64 encoding mismatch');
      report.pass(
        'Borsh',
        'i64 encoding',
        detail: 'value=${i64Ref["value"]}, hex=${i64Ref["hex"]}',
      );
    });

    test('booleans', () {
      final borshRefs = refs['borshEncoding'] as Map<String, dynamic>;

      final trueRef = borshRefs['bool_true'] as Map<String, dynamic>;
      final trueExpected = _jsonBytesToUint8List(trueRef['bytes'] as List);
      final trueDart = _encodePrimitive('bool', trueRef['value']);
      expect(
        trueDart,
        equals(trueExpected),
        reason: 'bool(true) encoding mismatch',
      );
      report.pass('Borsh', 'bool(true) encoding');

      final falseRef = borshRefs['bool_false'] as Map<String, dynamic>;
      final falseExpected = _jsonBytesToUint8List(falseRef['bytes'] as List);
      final falseDart = _encodePrimitive('bool', falseRef['value']);
      expect(
        falseDart,
        equals(falseExpected),
        reason: 'bool(false) encoding mismatch',
      );
      report.pass('Borsh', 'bool(false) encoding');
    });

    test('strings', () {
      final borshRefs = refs['borshEncoding'] as Map<String, dynamic>;

      final strRef = borshRefs['string'] as Map<String, dynamic>;
      final strExpected = _jsonBytesToUint8List(strRef['bytes'] as List);
      final strDart = _encodePrimitive('string', strRef['value']);
      expect(strDart, equals(strExpected), reason: 'string encoding mismatch');
      report.pass(
        'Borsh',
        'string encoding',
        detail: 'value="${strRef["value"]}", hex=${strRef["hex"]}',
      );

      final emptyRef = borshRefs['string_empty'] as Map<String, dynamic>;
      final emptyExpected = _jsonBytesToUint8List(emptyRef['bytes'] as List);
      final emptyDart = _encodePrimitive('string', emptyRef['value']);
      expect(
        emptyDart,
        equals(emptyExpected),
        reason: 'empty string encoding mismatch',
      );
      report.pass('Borsh', 'empty string encoding');

      final unicodeRef = borshRefs['string_unicode'] as Map<String, dynamic>;
      final unicodeExpected = _jsonBytesToUint8List(
        unicodeRef['bytes'] as List,
      );
      final unicodeDart = _encodePrimitive('string', unicodeRef['value']);
      expect(
        unicodeDart,
        equals(unicodeExpected),
        reason: 'unicode string encoding mismatch',
      );
      report.pass(
        'Borsh',
        'unicode string encoding',
        detail: 'value="${unicodeRef["value"]}"',
      );
    });
  });
}

// =============================================================================
// Helpers
// =============================================================================

/// Convert args from JSON representation to what the Dart encoder expects.
///
/// Key conversions:
/// - u64 string values → BigInt (JSON can't represent u64 precisely)
/// - u8 values stay as int
Map<String, dynamic> _convertArgsForEncoding(
  Map<String, dynamic> args,
  Idl idl,
  String ixName,
) {
  if (args.isEmpty) return args;

  // Find the instruction definition to know field types
  final ixDef = idl.instructions.firstWhere(
    (ix) => ix.name == ixName,
    orElse: () => throw StateError('Instruction $ixName not found in IDL'),
  );

  final converted = <String, dynamic>{};
  for (final entry in args.entries) {
    final argName = entry.key;
    final argValue = entry.value;

    // Find the type definition for this arg
    final argDef = ixDef.args.firstWhere(
      (a) => a.name == argName,
      orElse: () =>
          throw StateError('Arg $argName not found in instruction $ixName'),
    );

    final type = argDef.type;
    final typeStr = type.kind;

    if ((typeStr == 'u64' || typeStr == 'i64') && argValue is String) {
      // JSON-encoded large numbers come as strings
      converted[argName] = BigInt.parse(argValue);
    } else if ((typeStr == 'u64' || typeStr == 'i64') && argValue is int) {
      converted[argName] = BigInt.from(argValue);
    } else {
      converted[argName] = argValue;
    }
  }
  return converted;
}

/// Resolve an IDL type object to a simple string for type checking.
String _resolveTypeString(dynamic type) {
  if (type is String) return type;
  if (type is Map<String, dynamic>) {
    if (type.containsKey('vec')) return 'vec';
    if (type.containsKey('option')) return 'option';
    if (type.containsKey('array')) return 'array';
    if (type.containsKey('defined')) return 'defined';
  }
  return 'unknown';
}

/// Encode a single Borsh primitive value for verification against TS.
///
/// Uses the BorshSerializer from the instruction coder since that's what
/// the SDK uses to encode real instruction data.
Uint8List _encodePrimitive(String type, dynamic value) {
  final serializer = BorshSerializer();

  switch (type) {
    case 'u8':
      serializer.writeU8(value as int);
    case 'u16':
      serializer.writeU16(value as int);
    case 'u32':
      serializer.writeU32(value as int);
    case 'u64':
      final bigVal = value is String
          ? BigInt.parse(value)
          : BigInt.from(value as int);
      serializer.writeU64(bigVal);
    case 'i8':
      serializer.writeI8(value as int);
    case 'i16':
      serializer.writeI16(value as int);
    case 'i32':
      serializer.writeI32(value as int);
    case 'i64':
      final intVal = value is String ? int.parse(value) : value as int;
      serializer.writeI64(intVal);
    case 'bool':
      serializer.writeBool(value as bool);
    case 'string':
      serializer.writeString(value as String);
    default:
      throw ArgumentError('Unsupported primitive type: $type');
  }

  return serializer.toBytes();
}
