/// T2 — TS Reference Parity Tests
///
/// Loads reference values generated by the TypeScript SDK
/// and verifies Dart implementations match byte-for-byte.
///
/// Run: dart test test/component/ts_reference_parity_test.dart
@TestOn('vm')
library;

import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';

import 'package:coral_xyz/src/coder/discriminator_computer.dart';
import 'package:coral_xyz/src/coder/instruction_coder.dart';
import 'package:coral_xyz/src/idl/idl.dart';
import 'package:test/test.dart';

/// Load the references.json file.
Map<String, dynamic> loadReferences() {
  final file = File('test/reference/references.json');
  if (!file.existsSync()) {
    throw StateError(
      'references.json not found. Run: cd test/reference && node generate_references.mjs',
    );
  }
  return jsonDecode(file.readAsStringSync()) as Map<String, dynamic>;
}

/// Convert a hex string to Uint8List.

/// Convert camelCase to snake_case (matches Anchor's Rust function name convention).
String camelToSnakeCase(String input) => input
    .replaceAllMapped(RegExp(r'[A-Z]'), (m) => '_${m.group(0)!.toLowerCase()}')
    .replaceFirst(RegExp(r'^_'), '');
Uint8List hexToBytes(String hex) {
  final bytes = <int>[];
  for (var i = 0; i < hex.length; i += 2) {
    bytes.add(int.parse(hex.substring(i, i + 2), radix: 16));
  }
  return Uint8List.fromList(bytes);
}

/// Convert Uint8List to hex string.
String bytesToHex(Uint8List bytes) {
  return bytes.map((b) => b.toRadixString(16).padLeft(2, '0')).join();
}

/// Build a legacy-format Idl from raw JSON (old Anchor format).
Idl buildLegacyIdl(Map<String, dynamic> rawJson) {
  // Convert legacy format accounts to new format with discriminator array
  final instructions = (rawJson['instructions'] as List<dynamic>? ?? []).map((
    ix,
  ) {
    final ixMap = ix as Map<String, dynamic>;
    return {
      ...ixMap,
      'discriminator': <int>[], // Will be computed by the coder
    };
  }).toList();

  final accounts = (rawJson['accounts'] as List<dynamic>? ?? []).map((acc) {
    final accMap = acc as Map<String, dynamic>;
    return {'name': accMap['name'], 'discriminator': <int>[]};
  }).toList();

  final types = (rawJson['accounts'] as List<dynamic>? ?? []).map((acc) {
    final accMap = acc as Map<String, dynamic>;
    return {'name': accMap['name'], 'type': accMap['type']};
  }).toList();

  // Also include types[] from the IDL itself
  final extraTypes = (rawJson['types'] as List<dynamic>? ?? [])
      .cast<Map<String, dynamic>>();
  types.addAll(extraTypes);

  final events = (rawJson['events'] as List<dynamic>? ?? []).map((evt) {
    final evtMap = evt as Map<String, dynamic>;
    return {'name': evtMap['name'], 'discriminator': <int>[]};
  }).toList();

  final idlJson = {
    'address': '11111111111111111111111111111111', // Placeholder
    'metadata': {
      'name': rawJson['name'] ?? 'unknown',
      'version': rawJson['version'] ?? '0.0.0',
      'spec': '0.1.0',
    },
    'instructions': instructions,
    'accounts': accounts,
    'types': types,
    'events': events,
    'errors': rawJson['errors'] ?? [],
    'constants': rawJson['constants'] ?? [],
  };

  return Idl.fromJson(idlJson);
}

void main() {
  late Map<String, dynamic> refs;

  setUpAll(() {
    refs = loadReferences();
  });

  // ─────────────────────────────────────────────────────────────────────────
  // 1. Standalone Discriminator Tests
  // ─────────────────────────────────────────────────────────────────────────
  group('Standalone instruction discriminators', () {
    test('match TS SHA256("global:name") for well-known names', () {
      final standalone =
          refs['standaloneDiscriminators']['instructions']
              as Map<String, dynamic>;

      for (final entry in standalone.entries) {
        final name = entry.key;
        final expected = entry.value as Map<String, dynamic>;
        final expectedHex = expected['hex'] as String;

        final dartDisc = DiscriminatorComputer.computeInstructionDiscriminator(
          name,
        );
        final dartHex = bytesToHex(Uint8List.fromList(dartDisc));

        expect(
          dartHex,
          equals(expectedHex),
          reason:
              'Instruction discriminator mismatch for "$name": '
              'dart=$dartHex, ts=$expectedHex',
        );
      }
    });
  });

  group('Standalone account discriminators', () {
    test('match TS SHA256("account:Name") for well-known names', () {
      final standalone =
          refs['standaloneDiscriminators']['accounts'] as Map<String, dynamic>;

      for (final entry in standalone.entries) {
        final name = entry.key;
        final expected = entry.value as Map<String, dynamic>;
        final expectedHex = expected['hex'] as String;

        final dartDisc = DiscriminatorComputer.computeAccountDiscriminator(
          name,
        );
        final dartHex = bytesToHex(Uint8List.fromList(dartDisc));

        expect(
          dartHex,
          equals(expectedHex),
          reason:
              'Account discriminator mismatch for "$name": '
              'dart=$dartHex, ts=$expectedHex',
        );
      }
    });
  });

  group('Standalone event discriminators', () {
    test('match TS SHA256("event:Name") for well-known names', () {
      final standalone =
          refs['standaloneDiscriminators']['events'] as Map<String, dynamic>;

      for (final entry in standalone.entries) {
        final name = entry.key;
        final expected = entry.value as Map<String, dynamic>;
        final expectedHex = expected['hex'] as String;

        final dartDisc = DiscriminatorComputer.computeEventDiscriminator(name);
        final dartHex = bytesToHex(Uint8List.fromList(dartDisc));

        expect(
          dartHex,
          equals(expectedHex),
          reason:
              'Event discriminator mismatch for "$name": '
              'dart=$dartHex, ts=$expectedHex',
        );
      }
    });
  });

  // ─────────────────────────────────────────────────────────────────────────
  // 2. Program-specific discriminators
  // ─────────────────────────────────────────────────────────────────────────
  group('Program-specific discriminators', () {
    for (final programName in [
      'basic_counter',
      'clever_todo',
      'flutter_vote',
    ]) {
      group(programName, () {
        test('all instruction discriminators match TS', () {
          final program = refs['programs'][programName] as Map<String, dynamic>;
          final instructions = program['instructions'] as Map<String, dynamic>;

          for (final entry in instructions.entries) {
            final name = entry.key;
            final expected = entry.value as Map<String, dynamic>;
            final expectedHex = expected['discriminatorHex'] as String;

            // Legacy IDL stores camelCase names; Anchor uses snake_case for discriminators
            final snakeName = camelToSnakeCase(name);
            final dartDisc =
                DiscriminatorComputer.computeInstructionDiscriminator(
                  snakeName,
                );
            final dartHex = bytesToHex(Uint8List.fromList(dartDisc));

            expect(
              dartHex,
              equals(expectedHex),
              reason: '$programName.$name instruction discriminator',
            );
          }
        });

        test('all account discriminators match TS', () {
          final program = refs['programs'][programName] as Map<String, dynamic>;
          final accounts = program['accounts'] as Map<String, dynamic>;

          for (final entry in accounts.entries) {
            final name = entry.key;
            final expected = entry.value as Map<String, dynamic>;
            final expectedHex = expected['discriminatorHex'] as String;

            final dartDisc = DiscriminatorComputer.computeAccountDiscriminator(
              name,
            );
            final dartHex = bytesToHex(Uint8List.fromList(dartDisc));

            expect(
              dartHex,
              equals(expectedHex),
              reason: '$programName.$name account discriminator',
            );
          }
        });
      });
    }
  });

  // ─────────────────────────────────────────────────────────────────────────
  // 3. Encoded instruction parity
  // ─────────────────────────────────────────────────────────────────────────
  group('Encoded instruction parity', () {
    // Helper to load IDL from reference directory
    Map<String, dynamic> loadIdlJson(String filename) {
      final file = File('test/reference/$filename');
      return jsonDecode(file.readAsStringSync()) as Map<String, dynamic>;
    }

    group('basic_counter', () {
      late BorshInstructionCoder coder;
      late List<dynamic> encodedRefs;

      setUp(() {
        final rawIdl = loadIdlJson('basic_counter_idl.json');
        final idl = buildLegacyIdl(rawIdl);
        coder = BorshInstructionCoder(idl);
        final program =
            refs['programs']['basic_counter'] as Map<String, dynamic>;
        encodedRefs = program['encodedInstructions'] as List<dynamic>;
      });

      test('initialize encodes to match TS', () {
        final ref =
            encodedRefs.firstWhere((e) => e['instruction'] == 'initialize')
                as Map<String, dynamic>;
        final expectedHex = ref['hex'] as String;

        final dartBytes = coder.encode('initialize', {});
        final dartHex = bytesToHex(dartBytes);

        expect(
          dartHex,
          equals(expectedHex),
          reason: 'initialize encoding mismatch',
        );
      });

      test('increment(42) encodes to match TS', () {
        final ref =
            encodedRefs.firstWhere(
                  (e) =>
                      e['instruction'] == 'increment' &&
                      e['args']['amount'] == 42,
                )
                as Map<String, dynamic>;
        final expectedHex = ref['hex'] as String;

        final dartBytes = coder.encode('increment', {'amount': 42});
        final dartHex = bytesToHex(dartBytes);

        expect(
          dartHex,
          equals(expectedHex),
          reason: 'increment(42) encoding mismatch',
        );
      });

      test('increment(0) encodes to match TS', () {
        final ref =
            encodedRefs.firstWhere(
                  (e) =>
                      e['instruction'] == 'increment' &&
                      e['args']['amount'] == 0,
                )
                as Map<String, dynamic>;
        final expectedHex = ref['hex'] as String;

        final dartBytes = coder.encode('increment', {'amount': 0});
        final dartHex = bytesToHex(dartBytes);

        expect(
          dartHex,
          equals(expectedHex),
          reason: 'increment(0) encoding mismatch',
        );
      });

      test('increment(MAX_U64) encodes to match TS', () {
        final ref =
            encodedRefs.firstWhere(
                  (e) =>
                      e['instruction'] == 'increment' &&
                      e['args']['amount'].toString() == '18446744073709551615',
                )
                as Map<String, dynamic>;
        final expectedHex = ref['hex'] as String;

        final dartBytes = coder.encode('increment', {
          'amount': BigInt.parse('18446744073709551615'),
        });
        final dartHex = bytesToHex(dartBytes);

        expect(
          dartHex,
          equals(expectedHex),
          reason: 'increment(MAX_U64) encoding mismatch',
        );
      });
    });

    group('clever_todo', () {
      late BorshInstructionCoder coder;
      late List<dynamic> encodedRefs;

      setUp(() {
        final rawIdl = loadIdlJson('todo_idl.json');
        final idl = buildLegacyIdl(rawIdl);
        coder = BorshInstructionCoder(idl);
        final program = refs['programs']['clever_todo'] as Map<String, dynamic>;
        encodedRefs = program['encodedInstructions'] as List<dynamic>;
      });

      test('initializeUser encodes to match TS', () {
        final ref =
            encodedRefs.firstWhere((e) => e['instruction'] == 'initializeUser')
                as Map<String, dynamic>;
        final expectedHex = ref['hex'] as String;

        final dartBytes = coder.encode('initializeUser', {});
        final dartHex = bytesToHex(dartBytes);

        expect(
          dartHex,
          equals(expectedHex),
          reason: 'initializeUser encoding mismatch',
        );
      });

      test('addTodo("Buy groceries") encodes to match TS', () {
        final ref =
            encodedRefs.firstWhere((e) => e['instruction'] == 'addTodo')
                as Map<String, dynamic>;
        final expectedHex = ref['hex'] as String;

        final dartBytes = coder.encode('addTodo', {'content': 'Buy groceries'});
        final dartHex = bytesToHex(dartBytes);

        expect(
          dartHex,
          equals(expectedHex),
          reason: 'addTodo encoding mismatch',
        );
      });

      test('markTodo(3) encodes to match TS', () {
        final ref =
            encodedRefs.firstWhere((e) => e['instruction'] == 'markTodo')
                as Map<String, dynamic>;
        final expectedHex = ref['hex'] as String;

        final dartBytes = coder.encode('markTodo', {'todoIdx': 3});
        final dartHex = bytesToHex(dartBytes);

        expect(
          dartHex,
          equals(expectedHex),
          reason: 'markTodo encoding mismatch',
        );
      });
    });

    group('flutter_vote', () {
      late BorshInstructionCoder coder;
      late List<dynamic> encodedRefs;

      setUp(() {
        final rawIdl = loadIdlJson('voting_idl.json');
        final idl = buildLegacyIdl(rawIdl);
        coder = BorshInstructionCoder(idl);
        final program =
            refs['programs']['flutter_vote'] as Map<String, dynamic>;
        encodedRefs = program['encodedInstructions'] as List<dynamic>;
      });

      test('vote(1) encodes to match TS', () {
        final ref =
            encodedRefs.firstWhere((e) => e['instruction'] == 'vote')
                as Map<String, dynamic>;
        final expectedHex = ref['hex'] as String;

        final dartBytes = coder.encode('vote', {'voteId': 1});
        final dartHex = bytesToHex(dartBytes);

        expect(
          dartHex,
          equals(expectedHex),
          reason: 'vote(1) encoding mismatch',
        );
      });

      test('initialize(name, description, options) encodes to match TS', () {
        final ref =
            encodedRefs.firstWhere((e) => e['instruction'] == 'initialize')
                as Map<String, dynamic>;
        final expectedHex = ref['hex'] as String;

        final dartBytes = coder.encode('initialize', {
          'name': 'Best Language',
          'description': 'Vote for the best programming language',
          'options': ['Dart', 'Rust', 'TypeScript'],
        });
        final dartHex = bytesToHex(dartBytes);

        expect(
          dartHex,
          equals(expectedHex),
          reason: 'initialize(...) encoding mismatch',
        );
      });
    });
  });

  // ─────────────────────────────────────────────────────────────────────────
  // 4. Account size parity
  // ─────────────────────────────────────────────────────────────────────────
  group('Account size parity', () {
    for (final programName in [
      'basic_counter',
      'clever_todo',
      'flutter_vote',
    ]) {
      test('$programName account sizes match TS calculations', () {
        final program = refs['programs'][programName] as Map<String, dynamic>;
        final accountSizes = program['accountSizes'] as Map<String, dynamic>;

        for (final entry in accountSizes.entries) {
          final accName = entry.key;
          final ref = entry.value as Map<String, dynamic>;

          if (ref.containsKey('error')) continue; // Skip errored entries

          final isVariable = ref['isVariableLength'] as bool;
          if (isVariable) continue; // Skip variable-length accounts

          final expectedTotal = ref['totalSize'] as int;
          final expectedBody = ref['bodySize'] as int;
          final expectedDisc = ref['discriminatorSize'] as int;

          expect(
            expectedDisc,
            equals(8),
            reason: '$programName.$accName discriminator should be 8',
          );
          expect(
            expectedTotal,
            equals(expectedDisc + expectedBody),
            reason: '$programName.$accName total = disc + body',
          );
        }
      });
    }
  });

  // ─────────────────────────────────────────────────────────────────────────
  // 5. Borsh primitive encoding parity
  // ─────────────────────────────────────────────────────────────────────────
  group('Borsh primitive encoding parity', () {
    test('u8 encoding matches TS', () {
      final ref = refs['borshEncoding']['u8'] as Map<String, dynamic>;
      final expectedHex = ref['hex'] as String;
      final bytes = Uint8List(1);
      bytes.buffer.asByteData().setUint8(0, 42);
      expect(bytesToHex(bytes), equals(expectedHex));
    });

    test('u16 encoding matches TS', () {
      final ref = refs['borshEncoding']['u16'] as Map<String, dynamic>;
      final expectedHex = ref['hex'] as String;
      final bytes = Uint8List(2);
      bytes.buffer.asByteData().setUint16(0, 1000, Endian.little);
      expect(bytesToHex(bytes), equals(expectedHex));
    });

    test('u32 encoding matches TS', () {
      final ref = refs['borshEncoding']['u32'] as Map<String, dynamic>;
      final expectedHex = ref['hex'] as String;
      final bytes = Uint8List(4);
      bytes.buffer.asByteData().setUint32(0, 100000, Endian.little);
      expect(bytesToHex(bytes), equals(expectedHex));
    });

    test('u64 encoding matches TS', () {
      final ref = refs['borshEncoding']['u64'] as Map<String, dynamic>;
      final expectedHex = ref['hex'] as String;
      final bytes = Uint8List(8);
      bytes.buffer.asByteData().setUint64(0, 1000000000000, Endian.little);
      expect(bytesToHex(bytes), equals(expectedHex));
    });

    test('i8 encoding matches TS', () {
      final ref = refs['borshEncoding']['i8'] as Map<String, dynamic>;
      final expectedHex = ref['hex'] as String;
      final bytes = Uint8List(1);
      bytes.buffer.asByteData().setInt8(0, -42);
      expect(bytesToHex(bytes), equals(expectedHex));
    });

    test('i32 encoding matches TS', () {
      final ref = refs['borshEncoding']['i32'] as Map<String, dynamic>;
      final expectedHex = ref['hex'] as String;
      final bytes = Uint8List(4);
      bytes.buffer.asByteData().setInt32(0, -100000, Endian.little);
      expect(bytesToHex(bytes), equals(expectedHex));
    });

    test('bool true encoding matches TS', () {
      final ref = refs['borshEncoding']['bool_true'] as Map<String, dynamic>;
      final expectedHex = ref['hex'] as String;
      expect(bytesToHex(Uint8List.fromList([1])), equals(expectedHex));
    });

    test('bool false encoding matches TS', () {
      final ref = refs['borshEncoding']['bool_false'] as Map<String, dynamic>;
      final expectedHex = ref['hex'] as String;
      expect(bytesToHex(Uint8List.fromList([0])), equals(expectedHex));
    });

    test('string "hello world" encoding matches TS', () {
      final ref = refs['borshEncoding']['string'] as Map<String, dynamic>;
      final expectedHex = ref['hex'] as String;

      // Borsh string: 4-byte LE length + UTF8 bytes
      final strBytes = utf8.encode('hello world');
      final bytes = Uint8List(4 + strBytes.length);
      bytes.buffer.asByteData().setUint32(0, strBytes.length, Endian.little);
      bytes.setRange(4, 4 + strBytes.length, strBytes);
      expect(bytesToHex(bytes), equals(expectedHex));
    });

    test('empty string encoding matches TS', () {
      final ref = refs['borshEncoding']['string_empty'] as Map<String, dynamic>;
      final expectedHex = ref['hex'] as String;

      final bytes = Uint8List(4);
      bytes.buffer.asByteData().setUint32(0, 0, Endian.little);
      expect(bytesToHex(bytes), equals(expectedHex));
    });

    test('unicode string encoding matches TS', () {
      final ref =
          refs['borshEncoding']['string_unicode'] as Map<String, dynamic>;
      final expectedHex = ref['hex'] as String;

      final strBytes = utf8.encode('日本語');
      final bytes = Uint8List(4 + strBytes.length);
      bytes.buffer.asByteData().setUint32(0, strBytes.length, Endian.little);
      bytes.setRange(4, 4 + strBytes.length, strBytes);
      expect(bytesToHex(bytes), equals(expectedHex));
    });
  });
}
